In [128]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense, Input,Flatten,GlobalAveragePooling2D,SimpleRNN,LSTM,Bidirectional

from keras.models import Sequential

In [78]:
seq=[10,20,30,40,50,60,70,80,90]
steps=3
x=[]
y=[]
for i in range(len(seq)+1):
    if(len(seq)>steps+i):
        x.append(seq[i:i+steps])
        y.append(seq[i+steps])



In [79]:
x

[[10, 20, 30],
 [20, 30, 40],
 [30, 40, 50],
 [40, 50, 60],
 [50, 60, 70],
 [60, 70, 80]]

In [80]:
y

[40, 50, 60, 70, 80, 90]

In [81]:
x_arr=np.array([x])
x_arr=x_arr.reshape(6,3,1)
x_arr

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])

In [82]:
x_arr.shape

(6, 3, 1)

In [83]:
model=Sequential()
model.add(Input(shape=(3,1)))
model.add(SimpleRNN(50,activation='tanh',return_sequences=False,unroll=False))
model.add(Dense(10,activation='relu'))
model.add(Dense(1,activation='linear'))

In [84]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_4 (SimpleRNN)        │ (None, 50)             │         2,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 10)             │           510 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,121 (12.19 KB)

 Trainable params: 3,121 (12.19 KB)

 Non-trainable params: 0 (0.00 B)

In [85]:
model.compile(optimizer='sgd',loss='mse',metrics=['mse'])

In [86]:
y_arr = np.array(y)
model.fit(x_arr, y_arr, epochs=200, verbose=1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 4447.9956 - mse: 4447.9956
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 12204.0889 - mse: 12204.0889
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 13963.2148 - mse: 13963.2148
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 3029.2637 - mse: 3029.2637
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 820686.2500 - mse: 820686.2500
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 6791.4844 - mse: 6791.4844
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 6534.0918 - mse: 6534.0918
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 6286.8906 - mse: 6286.8906
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 6049.4800 - mse: 6049.4800
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 5821.4712 - mse: 5821.4712
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5602.4902 - mse: 5602.4902
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss

In [87]:
print(x_arr.shape)
print(y_arr.shape)

(6, 3, 1)
(6,)


In [88]:
x_arr

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])

In [89]:
test=[70,80,90]
test=np.array(test)
test=test.reshape(1,3,1)
test.shape

(1, 3, 1)

In [ ]:
model.predict(test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 429ms/step


array([[63.431324]], dtype=float32)

In [119]:
model1=Sequential()
model1.add(Input(shape=(3,1)))
model1.add(LSTM(64,activation='relu'))
model1.add(Dense(32,activation='relu'))
model1.add(Dense(1,activation='linear'))
model1.compile(optimizer='adam',loss='mse')
model1.fit(x_arr, y_arr, epochs=250, verbose=1)

Epoch 1/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 3579.0798
Epoch 2/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 3463.2117
Epoch 3/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 3353.7734
Epoch 4/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 3250.6379
Epoch 5/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 3148.6904
Epoch 6/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 3047.6223
Epoch 7/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 2948.2087
Epoch 8/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2844.8718
Epoch 9/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2736.3997
Epoch 10/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2625.3630
Epoch 11/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2515.1619
Epoch 12/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2403.0366
Epoch 13/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2288.5276
Epoch 14/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2170.8706
Epoch 15/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms

In [124]:
model1.predict(test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step


array([[100.31187]], dtype=float32)

In [122]:

model1.fit(x_arr, y_arr, epochs=250, verbose=1)

Epoch 1/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0014
Epoch 2/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0014
Epoch 3/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0014
Epoch 4/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0014
Epoch 5/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0014
Epoch 6/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0014
Epoch 7/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0013
Epoch 8/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0013
Epoch 9/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.0013
Epoch 10/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0013
Epoch 11/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0013
Epoch 12/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0013
Epoch 13/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0013
Epoch 14/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0013
Epoch 15/250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0013
Epoch 16/250
1/1 ━━

In [ ]:
#MULITI LAYER LSTM

model = Sequential()
model.add(Input(shape=x_arr[0].shape))
model.add(LSTM(50,activation="relu",return_sequences=True))
model.add(LSTM(50,activation="relu"))
model.add(Dense(1))

model.compile(optimizer="adam",loss="mean_squared_error")
model.fit(x_arr,y_arr,epochs=200)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - loss: 4739.9258
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 4699.2300
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 4658.8418
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 4618.2632
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 4577.0938
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 4535.1499
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 4492.4673
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 4448.9370
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 4404.3594
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 4358.1235
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 4309.6929
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 4258.8164
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 4204.4756
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 4146.3354
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms

In [132]:
#BIDIRECTIONAL LSTM
model = Sequential()
model.add(Input(shape=x_arr[0].shape))
model.add(Bidirectional(LSTM(50,activation="relu")))
model.add(Dense(1))

model.compile(optimizer="Adam",loss="mse")
model.fit(x_arr,y_arr,epochs=200,verbose=1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - loss: 3394.0618
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 3301.4426
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 3210.9033
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 3121.5339
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 3031.7649
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2940.7334
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2849.2080
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2756.7883
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2663.0269
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2567.4739
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2469.6941
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 2369.5759
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 2266.7122
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2160.6392
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms