In [1]:
import tensorflow as tf  
print("version of the tensorflow :",tf.__version__)
print("GPU available :",tf.config.list_physical_devices('GPU'))

version of the tensorflow : 2.20.0
GPU available : []


In [6]:
scalar= tf.constant(42)
vector = tf.constant([1,2,3,4])
matrix=tf.constant([[1,-2],[2,-3]])
tensor_3d=tf.constant([[[1,2,3],[4,5,6]]])
print(f"\n scalar shape {scalar.shape},value :{scalar.numpy} :")
print(f"\n vector shape {vector.shape},value :{vector.numpy} :")
print(f"\n matrix shape {matrix.shape},value :{matrix.numpy} :")
print(f"\n tesnor_3d shape {tensor_3d.shape},value: {tensor_3d.numpy}")


 scalar shape (),value :<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=42>> :

 vector shape (4,),value :<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>> :

 matrix shape (2, 2),value :<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1, -2],
       [ 2, -3]], dtype=int32)>> :

 tesnor_3d shape (1, 2, 3),value: <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>>


In [8]:
print(f"thensor dtype :{tensor_3d.dtype}")
print(f"tensor rank means dimensions of that variable :{tf.rank(tensor_3d).numpy()}")
print(f"tensor size :{tf.size(tensor_3d).numpy()}")

thensor dtype :<dtype: 'int32'>
tensor rank means dimensions of that variable :3
tensor size :6


In [10]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[4,5],[5,6]])
print("the addition of matrix is:",tf.add(a,b))
print("the sub of matrix is:",tf.subtract(a,b))
print("the multply element of matrix is:",tf.multiply(a,b))
print("the   matrix multiplocation is:",tf.matmul(a,b))

the addition of matrix is: tf.Tensor(
[[ 5  7]
 [ 8 10]], shape=(2, 2), dtype=int32)
the sub of matrix is: tf.Tensor(
[[-3 -3]
 [-2 -2]], shape=(2, 2), dtype=int32)
the multply element of matrix is: tf.Tensor(
[[ 4 10]
 [15 24]], shape=(2, 2), dtype=int32)
the   matrix multiplocation is: tf.Tensor(
[[14 17]
 [32 39]], shape=(2, 2), dtype=int32)


In [14]:
x=tf.constant([1.0,2.0,3.0])
print(f"the squre of matrix is :,{tf.square(x).numpy()}")
print(f"the squre root of matrix is :,{tf.sqrt(x).numpy()}")
print(f"the exponential  of matrix is :,{tf.exp(x).numpy()}")

the squre of matrix is :,[1. 4. 9.]
the squre root of matrix is :,[1.        1.4142135 1.7320508]
the exponential  of matrix is :,[ 2.7182817  7.389056  20.085537 ]


In [26]:
weigths=tf.Variable([[1.0,2.0],[3.0,4.0]],name='weights')
bias=tf.Variable([1.0,4.0,3.0],name='bias')
weigths


<tf.Variable 'weights:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [27]:
weigths.assign([[2.0,4.0],[7.0,5.0]])
weigths

<tf.Variable 'weights:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 4.],
       [7., 5.]], dtype=float32)>

In [28]:
weigths.assign_add([[3.0, 6.0],
                    [3.0, 6.0]])

weigths

<tf.Variable 'weights:0' shape=(2, 2) dtype=float32, numpy=
array([[ 5., 10.],
       [10., 11.]], dtype=float32)>