In [1]:
import tensorflow as tf

In [2]:
# 1. Create a scalar tensor with value 10 using tf.constant and print its value and data type.
scaler=tf.constant([10,20,30,40,50,60,70,80,90,100])
scaler

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100], dtype=int32)>

In [3]:
# 2. Create a 1-D tensor (vector) [2, 4, 6, 8] using tf.constant and print its shape and numpy value.
oned_tensor=tf.constant([2, 4, 6, 8])
print(f"the shape is {oned_tensor.shape},the value are:{oned_tensor.numpy()}")

the shape is (4,),the value are:[2 4 6 8]


In [4]:
# 3. Create a 2-D tensor (matrix) [[1, 2], [3, 4]] using tf.constant and print its shape and dtype.

twoD_tensor=tf.constant([[1, 2], [3, 4]])
print(f"the shape is {twoD_tensor.shape},the value are:{twoD_tensor.numpy()}")

the shape is (2, 2),the value are:[[1 2]
 [3 4]]


In [5]:
# 4. Create a tf.Variable with initial value 5.0 and print its current value.
var=tf.Variable(5.0)
print("the varible tf  value is :",var.numpy())

the varible tf  value is : 5.0


In [6]:
# 5. Update the above variable by assigning it a new value 10.0 using assign() and print the updated value.
var.assign(10.0)
print("now the updated var value is :",var.numpy())

now the updated var value is : 10.0


In [7]:

# 6. Use assign_add() on a variable initialized with [[1.0, 2.0], [3.0, 4.0]] to add 1.0 to every element and print the result.

arr=tf.Variable([[1.0, 2.0], [3.0, 4.0]])
print("\n intial it is:\n",arr.numpy())
arr.assign_add([[1.0,1.0],[1.0,1.0]])
print("\n after add 1.0 to every element: \n",arr.numpy())


 intial it is:
 [[1. 2.]
 [3. 4.]]

 after add 1.0 to every element: 
 [[2. 3.]
 [4. 5.]]


In [8]:

# 7. Create a variable x = 3.0 and inside a tf.GradientTape() block compute y = x**2 + 2*x + 1, then print both x and y.
x=tf.Variable(3.0)
y=tf.GradientTape(x**2+2*x+1)
print(f"the value of x is :{x.numpy()} the value of y is : {y} ")


the value of x is :3.0 the value of y is : <tensorflow.python.eager.backprop.GradientTape object at 0x000001203ABC3E00> 


In [9]:
# 9. Create two constant tensors a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]] and perform matrix multiplication using tf.matmul().
a=tf.constant([[1, 2], [3, 4]])
b=tf.constant([[5, 6], [7, 8]])
print('the matrix multiplication is :\n',tf.matmul(a,b).numpy())

the matrix multiplication is :
 [[19 22]
 [43 50]]


In [10]:
# 10. Create a random tensor of shape (3, 3) using tf.random.uniform() and print its shape, dtype, and values.
a=tf.random.uniform((3,3))
print(f"the shape of the random matrix is :{a.shape} the dtype is :{a.dtype} the values is:\n{a.numpy()}")

the shape of the random matrix is :(3, 3) the dtype is :<dtype: 'float32'> the values is:
[[0.7714523  0.3254038  0.69194245]
 [0.80216146 0.10524428 0.6672784 ]
 [0.40771508 0.24915051 0.98523605]]
