In [1]:
import numpy as np


In [2]:
arr1=np.array([10,20,30])
arr2=np.array([
    [10,20,30],
    [40,50,60]
])
arr3=np.array([[
    [10,20,30],
    [40,50,60],
    [70,80,90]
]])
print("1d array is:\n",arr1)
print("2d array is:\n",arr2)
print("3d array is:\n",arr3)

1d array is:
 [10 20 30]
2d array is:
 [[10 20 30]
 [40 50 60]]
3d array is:
 [[[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [4]:
#array prop
print("dimension is:",arr3.ndim)
print("the size of arr3 is:",arr3.size)
print("the shape of arr3 is",arr3.shape)
print("the dtype of arr3 is",arr3.dtype)

dimension is: 3
the size of arr3 is: 9
the shape of arr3 is (1, 3, 3)
the dtype of arr3 is int64


In [6]:
zeros=np.zeros((2,3))
ones=np.ones((3,3))
eye=np.eye(3)
rand=np.random.rand(2,3)
arrange_arr=np.arange(0,10,2)
linspace_arr=np.linspace(0,1,5)

print("\n the zeros array is :\n",zeros)
print("\n the ones array is :\n",ones)
print("\n the identical matrix array is :\n",eye)
print("\n the random   arry is :\n",rand)
print("\n the even  array is :\n",arrange_arr)
print("\n the linspace array is :\n",linspace_arr)


 the zeros array is :
 [[0. 0. 0.]
 [0. 0. 0.]]

 the ones array is :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 the identical matrix array is :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 the random   arry is :
 [[0.98162218 0.24401968 0.96956146]
 [0.77194799 0.05921364 0.03627627]]

 the even  array is :
 [0 2 4 6 8]

 the linspace array is :
 [0.   0.25 0.5  0.75 1.  ]


In [10]:
print("\n the  1d array:\n",arr1)
print("\n 1st element in 1d array:\n",arr1[0])
print("\n 2st element in 1d array:\n",arr1[2])
print("\n 1t0 2 element in 1d array:\n",arr1[1:3])
print("\n 2 step element in 1d array:\n",arr1[::2])



 the  1d array:
 [10 20 30]

 1st element in 1d array:
 10

 2st element in 1d array:
 30

 1t0 2 element in 1d array:
 [20 30]

 2 step element in 1d array:
 [10 30]


In [14]:
print("\n 2d array:\n",arr2)
print("\n 2,1 ele in 2d array:\n",arr2[1,2])
print("\n for 2 row 2 step 2d array:\n",arr2[:2,::2])


 2d array:
 [[10 20 30]
 [40 50 60]]

 2,1 ele in 2d array:
 60

 for 2 row 2 step 2d array:
 [[10 30]
 [40 60]]


In [19]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print("\n the addtition is of two array is :",a+b)
print("\n the sub is of two array is :",a-b)
print("\n the mult is of two array is :",a*b)
print("\n the division is of two array is :",a/b)




 the addtition is of two array is : [ 6  8 10 12]

 the sub is of two array is : [-4 -4 -4 -4]

 the mult is of two array is : [ 5 12 21 32]

 the division is of two array is : [0.2        0.33333333 0.42857143 0.5       ]


In [22]:
print("\n the max is of two array is :",arr2.max())

print("\n the min is of two array is :",arr2.min())

print("\n the mean is of two array is :",arr2.mean())






 the max is of two array is : 60

 the min is of two array is : 10

 the mean is of two array is : 35.0


In [25]:
arr_3=np.arange(1,15)
print("\n the orignal array is:\n",arr_3)
re=arr_3.reshape(2,7)
print("\n the reshape array is :",re)
print("\n the 2d flatten array is : ",arr2.flatten())


 the orignal array is:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

 the reshape array is : [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

 the 2d flatten array is :  [10 20 30 40 50 60]


In [28]:
#vstack and h stack
a=[[10,20],[30,40]]
b=[[50,60],[70,80]]
print("\n the h stacked array is:\n",np.hstack((a,b)))
print("\n the v stacked array is:\n",np.vstack((a,b)))


 the h stacked array is:
 [[10 20 50 60]
 [30 40 70 80]]

 the v stacked array is:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [29]:
a=np.array([10,12,43,21])
filter_arr=a>15
print("\nfilter the array:",filter_arr)
print("\nthe filtered array is :",a[filter_arr])



filter the array: [False False  True  True]

the filtered array is : [43 21]


In [ ]:
print("\nRandom integer 1-100:",np.random.randint(1,100))
print("\n Random ")